apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secret
  namespace: task-manager
type: Opaque
stringData:
  # IMPORTANTE: cambia este valor en producción y nunca lo subas a git.
  # En CI/CD se sobreescribe vía: kubectl create secret generic ...
  SPRING_DATASOURCE_PASSWORD: "postgres"
  JWT_SECRET: "dGFza21hbmFnZXItand0LXNlY3JldC1rZXktMjAyNi1kby1ub3QtdXNlLWluLXByb2R1Y3Rpb24="
